### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by adiputera** [btcmp/bootcamp137_-3#1]
NullPointerException kalau data yang diambil null

**Comment by arrizaqu** [comment]
NullPointerException bukan karena data yang diambil null, tapi Null tersebuat karena kemungkinan ada penggunaan object yang belum terinstansiasi,

**Comment by adiputera** [comment]
ternyata karena perulangan dengan data yang diambil, jadi jika yang diambil null, perulangannya error, solusi : cek apakah data null sebelum melakukan perulangan
